name: app_educatif
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  flame: ^1.16.0
  flame_audio: ^2.11.5
  http: 1.3.0 
  shared_preferences: ^2.5.3 
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.7
  animated_notch_bottom_bar: ^1.0.0
  provider: ^6.1.1
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  assets:
    - assets/images/start_app.jpg
    - assets/images/onbording.jpeg
    - assets/images/map_background.png
    - assets/images/map_background.jpg
    - assets/images/character_icon.png
    - assets/images/Bunnie.png
    - assets/images/app_icon.jpeg
    - assets/images/splash_page.jpeg
    - assets/icons/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpeg"
  min_sdk_android: 21 
  adaptive_icon_background: "#FFFFFF"
